name: Deploy to Production

on: push

env:
  MY_NAME: "Rafael"

jobs:
  first_jobs: # Identifier for the first job
    name: Mi primer job # Name of the job que se verá refleajado en la interfaz de GitHub
    id: step_1
    runs-on: ubuntu-latest
    env: 
      OS_ENV: "Linux"
    steps:
      - name: Hola Mundo
        run: echo "Hola ${MY_NAME}, bienvenido a GitHub Actions, Estás en el primer job en ${OS_ENV}"
      - name: Información del sistema
        run: cat /etc/os-release
      - name: ver rama acual
        run: echo "La rama actual es ${{ github.ref }}"
      - name: ver directorio actual
        run: ls -la
      - name: Actions
        uses: actions/checkout@v4 # This step checks out the repository so that the workflow can access its contents
      - name: Variable de entorno
        run: echo "my_variable=Hola" >> $GITHUB_OUTPPUT
      - name: salida de variable de entorno
        run: echo "La variable de entorno es ${{ steps.step_1.outputs.my_variable }}"
    
    outputs:
      my_variable: ${{ steps.step_1.outputs.my_variable }} # Output variable from the first job
        
  second_jobs:
    needs: first_jobs # This job depends on the first job
    if: ${{github.ref == 'refs/heads/main'}} # Only run on main branch, los if se pueden definir también en los steps
    runs-on: macOS-latest

    env: 
      OS_ENV: "macOS"
      my_variable: ${{ needs.first_jobs.outputs.my_variable }} # Accessing output variable from the first job

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${MY_NAME}, Estás en el segundo job en ${OS_ENV}"
      - name: Información del sistema
        run: sw_vers
      - name: la variable compartida es
        run: echo "La variable compartida es ${my_variable}"