name: "Deploy Codigo Facilito"

on:
  push:
    branches:
      - main

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest # Define el sistema operativo en el que se ejecutar치 el job
    steps: # Define los pasos que se ejecutar치n en el job
    - name: Checkout code
      uses: actions/checkout@v2 # Clona el repositorio en el runner
      run: echo "se realiza pull del c칩digo"  # Paso 1: Clonar el repositorio
      run: echo "correr migraciones"
      run: echo "publicar versi칩n"