name: Deploy to Production

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
      - name: Información del sistema
        run: cat /etc/os-release
  
  second_jobs:
    needs: first_jobs # This job depends on the first job
    runs-on: macOS-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
      - name: Información del sistema
        run: sw_vers