name: Deploy to Production

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      MY_NAME: "Rafael"

    steps:
      - name: Hola Mundo
        run: echo "Hola ${MY_NAME}, bienvenido a GitHub Actions"
      - name: Información del sistema
        run: cat /etc/os-release
      - name: ver rama acual
        run: echo "La rama actual es ${{ github.ref }}"
  
  second_jobs:
    needs: first_jobs # This job depends on the first job
    if: ${{github.ref == 'refs/heads/main'}} # Only run on main branch, los if se pueden definir también en los steps
    runs-on: macOS-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
      - name: Información del sistema
        run: sw_vers