name: Deploy to Production

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
  
  second_jobs:
    runs-on: macOS-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"